version: '3.1'

services :
  php:
    image: php:7-apache
    volumes:
      - .:/var/www/html
    ports:
      - 80:80
  
  composer:
    image: composer/composer:php7
    command: install
    volumes:
      - .:/app
      
  mysql:
    image: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password