version: '3.1'

services :
  php:
    build: .
    volumes:
      - .:/var/www/html
    ports:
      - 80:80
        
  composer:
    image: composer:latest
    command: install
    command: update
    volumes:
      - .:/app
  
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - db

  db:
    image: mysql
    command: mysqld --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password